### ISSUE TITLE
建议移除“程序员鱼皮”

### ISSUE THREAD

**Issue by jsun969** [SyMind/awesome-bilibili#2]
另外，我建议移除“程序员鱼皮”。此人视频含金量较少，并以向入门者推销他的知识星球“割韭菜”。同时在任何腾讯参股的社交平台中，无法发布有关批判他的文章（知乎，脉脉）。

我曾发布过一篇有关博文（可能较激进）：https://jsun.lol/blog/rubbish-liyupi

_Originally posted by @jsun969 in https://github.com/SyMind/awesome-bilibili/issues/1#issuecomment-1419192672_

**Comment by SyMind** [comment]
@jsun969 本仓库目的是想收集更多能让人学到技术的 up 主，我会认真浏览他的所有视频判断后答复你，这个 issue 先 open。

**Comment by SyMind** [comment]
@jsun969 已经移除。
