### ISSUE TITLE
阿婆主推荐

### ISSUE THREAD

**Issue by Wyatex** [SyMind/awesome-bilibili#5]
我个人觉得还不错的一些阿婆主

机器学习：
- [生姜DrGinger](https://space.bilibili.com/513194466)

前端：
- [哲玄前端](https://space.bilibili.com/3493279159028558)
- [前端小野森森-1](https://space.bilibili.com/378372969)
- [前端小野森森-2](https://space.bilibili.com/492976859)
- [CodingStartup起码课](https://space.bilibili.com/451368848)
- [山羊の前端小窝](https://space.bilibili.com/266664645)

后端：
- [面向加薪学习](https://space.bilibili.com/375038855)
- [Go夜读](https://space.bilibili.com/326749661)
- [遇见狂神说](https://space.bilibili.com/95256449)

通用编程技能:
- [GeekHour](https://space.bilibili.com/102438649)

**Comment by SyMind** [comment]
@Wyatex 感谢你的推荐，我会在本周加入。
