### ISSUE TITLE
求 C++ 相关的 up 主

### ISSUE THREAD

**Issue by herman-leung** [SyMind/awesome-bilibili#6]
有没有c++的啊

**Comment by SyMind** [comment]
@herman-leung 我对 C++ 不是很了解，你可以改一下 issue 标题，然后等一个有缘人 PR。

**Comment by SyMind** [comment]
碰巧搜索 Rust 相关视频时看到这个 up 主：https://github.com/SyMind/awesome-bilibili/commit/05eab9dc2c334faebac998e86de8d665253dd9d0
